const stores={repair:'verge-repair',products:'verge-products',chartering:'verge-chartering'};
const state={repair:load(stores.repair),products:load(stores.products),chartering:load(stores.chartering)};
const titles={home:'Overview',repair:'Repair',products:'Products',chartering:'Chartering'};
const cp=[['SUPPLYTIME','Offshore support vessels, PSV, AHTS and OSV work.'],['TOWCON','Lump sum ocean towage.'],['TOWHIRE','Daily hire ocean towage.'],['BARECON','Bareboat charter.'],['HEAVYCON','Heavy lift and project cargo.'],['PROJECTCON','Project cargo work.'],['GENCON','Voyage charter reference.'],['NYPE','Time charter reference.'],['WINDTIME','Offshore wind support.']];
const demo={repair:[{vessel:'MV Demo',port:'Piraeus',type:'Underwater',eta:'18 June',status:'Sourcing',priority:'Urgent',scope:'IWS, propeller polishing and sea chest cleaning.',privateNotes:'Private chain notes.'}],products:[{vessel:'Bulker Demo',equipment:'Hatch cover rubber',maker:'TTS',model:'TBA',partNumber:'C2553-94x55',delivery:'Urgent',status:'Sourcing',priority:'Urgent',notes:'60 pcs. Confirm EPDM and delivery.'}],chartering:[{vessel:'52m AHT, 106 TBP',type:'AHT / Tug',location:'East Med',availability:'Prompt',rate:'Owners to advise',status:'Hot',publicNotes:'240 sqm deck space, towing support.',privateNotes:'Private source notes.'}]};
function load(k){try{return JSON.parse(localStorage.getItem(k))||[]}catch{return[]}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v){return String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function show(id){document.querySelectorAll('.module-section').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.section===id));document.getElementById('viewTitle').textContent=titles[id]||'Overview'}
document.querySelectorAll('.nav-item').forEach(n=>n.onclick=()=>show(n.dataset.section));document.querySelectorAll('[data-jump]').forEach(n=>n.onclick=()=>show(n.dataset.jump));
function data(form){return Object.fromEntries(new FormData(form).entries())}
function bind(id,bucket){document.getElementById(id).onsubmit=e=>{e.preventDefault();state[bucket].unshift({...data(e.target),createdAt:new Date().toISOString()});save(stores[bucket],state[bucket]);e.target.reset();render();toast('Saved')}}
bind('repairForm','repair');bind('productForm','products');bind('charterForm','chartering');
function empty(t,c,msg){t.innerHTML=`<tr><td colspan="${c}">${msg}</td></tr>`}
function actions(b,i){return `<div class="row-actions"><button class="text-button" onclick="copyRow('${b}',${i})">Copy</button><button class="text-button" onclick="delRow('${b}',${i})">Delete</button></div>`}
function renderRepair(){const t=document.getElementById('repairTable');if(!state.repair.length)return empty(t,7,'No repair cases yet.');t.innerHTML=state.repair.map((x,i)=>`<tr><td><span class="table-main">${esc(x.vessel)}</span><span class="table-note">${esc(x.scope)}</span></td><td>${esc(x.type)}</td><td>${esc(x.port||'TBA')}</td><td>${esc(x.eta||'TBA')}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td><span class="badge ${esc(x.priority)}">${esc(x.priority)}</span></td><td>${actions('repair',i)}</td></tr>`).join('')}
function renderProducts(){const t=document.getElementById('productTable');if(!state.products.length)return empty(t,7,'No product enquiries yet.');t.innerHTML=state.products.map((x,i)=>`<tr><td><span class="table-main">${esc(x.equipment)}</span><span class="table-note">${esc(x.notes)}</span></td><td>${esc(x.maker||'TBA')}</td><td>${esc(x.model||'TBA')}</td><td>${esc(x.partNumber||'TBA')}</td><td>${esc(x.delivery||'TBA')}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td>${actions('products',i)}</td></tr>`).join('')}
function renderChartering(){const t=document.getElementById('charterTable');if(!state.chartering.length)return empty(t,7,'No vessel positions yet.');t.innerHTML=state.chartering.map((x,i)=>`<tr><td><span class="table-main">${esc(x.vessel)}</span><span class="table-note">${esc(x.publicNotes)}</span></td><td>${esc(x.type)}</td><td>${esc(x.location||'TBA')}</td><td>${esc(x.availability||'TBA')}</td><td>${esc(x.rate||'TBA')}</td><td><span class="badge ${esc(x.status)}">${esc(x.status)}</span></td><td>${actions('chartering',i)}</td></tr>`).join('')}
function delRow(b,i){state[b].splice(i,1);save(stores[b],state[b]);render();toast('Deleted')}
function copyRow(b,i){const x=state[b][i];let txt='';if(b==='repair')txt=`Good day,\n\nPlease advise availability and offer basis below request:\n\n***Q***\nVessel / Ref: ${x.vessel||'TBA'}\nPort / Area: ${x.port||'TBA'}\nETA / Window: ${x.eta||'TBA'}\nService type: ${x.type||'TBA'}\nScope: ${x.scope||'TBA'}\n***UQ***\n\nPlease consider 10% commission for our office and 30 days payment terms.\n\nAlways at your disposal.`;if(b==='products')txt=`Good day,\n\nPlease advise price and availability for below enquiry:\n\n***Q***\nEquipment: ${x.equipment||'TBA'}\nMaker: ${x.maker||'Please confirm'}\nModel: ${x.model||'Please confirm'}\nPart number: ${x.partNumber||'Please confirm'}\nRequired delivery time: ${x.delivery||'Please confirm'}\nNotes: ${x.notes||'TBA'}\n***UQ***\n\nPlease confirm maker, model, part number, and required delivery time.\n\nPlease consider 10% commission for our office and 30 days payment terms.\n\nAlways at your disposal.`;if(b==='chartering')txt=`Good day,\n\nPlease advise whether below unit may be available:\n\nVessel / Ref: ${x.vessel||'TBA'}\nType: ${x.type||'TBA'}\nLocation: ${x.location||'TBA'}\nAvailability: ${x.availability||'TBA'}\nRate indication: ${x.rate||'TBA'}\nNotes: ${x.publicNotes||'TBA'}\n\nAll details are given in good faith, subject to final confirmation.\n\nAlways at your disposal.`;copy(txt)}
document.querySelectorAll('[data-template]').forEach(b=>b.onclick=()=>copy(`Good day,\n\nPlease advise availability and offer basis below request:\n\n***Q***\nRequirement: TBA\nArea / Port: TBA\nTiming: TBA\nScope: TBA\n***UQ***\n\nPlease consider 10% commission for our office and 30 days payment terms.\n\nAlways at your disposal.`));
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>exportCsv(b.dataset.export));
function exportCsv(b){const rows=state[b];if(!rows.length)return toast('Nothing to export');const h=Object.keys(rows[0]);const csv=[h,...rows.map(r=>h.map(k=>r[k]||''))].map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`verge-${b}.csv`;a.click();URL.revokeObjectURL(url)}
function copy(t){navigator.clipboard.writeText(t).then(()=>toast('Copied'))}
function toast(m){const n=document.getElementById('toast');n.textContent=m;n.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>n.classList.remove('show'),1600)}
function renderCP(){document.getElementById('cpGrid').innerHTML=cp.map(x=>`<article class="cp-card"><h4>${esc(x[0])}</h4><p>${esc(x[1])}</p><div class="cp-tags"><span>Reference</span></div></article>`).join('')}
function metrics(){document.getElementById('repairMetric').textContent=state.repair.length;document.getElementById('productMetric').textContent=state.products.length;document.getElementById('charterMetric').textContent=state.chartering.length}
function render(){renderRepair();renderProducts();renderChartering();metrics()}
document.getElementById('seedAll').onclick=()=>{state.repair=[...demo.repair,...state.repair];state.products=[...demo.products,...state.products];state.chartering=[...demo.chartering,...state.chartering];save(stores.repair,state.repair);save(stores.products,state.products);save(stores.chartering,state.chartering);render();toast('Demo data loaded')};
window.delRow=delRow;window.copyRow=copyRow;renderCP();render();